### ISSUE TITLE
it said no module named clearbit : i cant find the folder of this module ( clearbit ) 

### ISSUE THREAD

**Issue by pretech86** [SharadKumar97/OSINT-SPY#13]

**Comment by pretech86** [comment]
me too have this problem

**Comment by pretech86** [comment]
i solved it

**Comment by D3m0ni4k** [comment]
pip3 install clearbit enjoy it 😉

**Comment by MaeKing** [comment]
I swear if it's that simple.... I'm just gonna be hell a dipshit


-------- Original message --------

**Comment by MaeKing** [comment]
Can you offer any of that AWESOME assistance on sn0int... it spins up... cant load the "GeoIP2 database" .. we will put a stocking up for you EVERY YEAR if you can...

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by SharadKumar97** [comment]
The codebase has been updated, please do a git pull and use requirements.txt file. Thanks

**Comment by cryp70n1ccc** [comment]
pls help me i have the same problem no module named clearit. i have install it with pip3 install clearbit but nothing.

**Comment by 7h3h4ckv157** [comment]
sudo pip3 install clearbit
