### ISSUE TITLE
can't install in windows 

### ISSUE THREAD

**Issue by pretech86** [SharadKumar97/OSINT-SPY#15]
PS D:\shared_folder_for_virtual_machines\OSINT-SPY-master> python install_windows.py
Fatal error in launcher: Unable to create process using '"'
Fatal error in launcher: Unable to create process using '"'
Fatal error in launcher: Unable to create process using '"'
Fatal error in launcher: Unable to create process using '"'
Fatal error in launcher: Unable to create process using '"'
Fatal error in launcher: Unable to create process using '"'
PS D:\shared_folder_for_virtual_machines\OSINT-SPY-master>

can you help please

**Comment by NFWADC** [comment]
had the same problem i run it on ubuntu sub system and had to manually install all the programs that install_windows.py does........... FIX - run all these commands manually 

pip install clearbit

pip install shodan

pip install fullcontact.py

pip install steganography

pip install requests

pip install sslscan

**Comment by SharadKumar97** [comment]
Now using requirements.txt, so it should not be an issue now.
