### ISSUE TITLE
- - email no longer works 

### ISSUE THREAD

**Issue by OSINT007** [SharadKumar97/OSINT-SPY#16]
I have been using this tool and it is amazing. However, the - - email command has stopped giving any relevant information. I’ve tried to uninstall and install but still no information is retrieved. I tried with a sample email that always worked but nothing comes back. All fields empty. Please help! Any clues?

**Comment by SharadKumar97** [comment]
We are working on this tool. In coming days, you will get this bug fixed and will get lot of cool features.

**Comment by OSINT007** [comment]
Sweet!!!! Thanks so much! I’m a big fan!

**Comment by pretech86** [comment]
thanks for your interest and waitong the update 
best regards

**Comment by darknodi** [comment]
@OSINT007 can you add the alphabets syntaxes, the alphabet pronounciations, the alphabet compositions, of this script, is useful, but, need require key from api services, can you make with nokeycredentialfrom service, https://github.com/am0nt31r0/OSINT-Search


can you add even this script https://github.com/hkm/whoishere.py 

from this script, I will pay, if you add in this script, to see, password instagram, from whoishere.py, 
this script detects firstname and lastname, from the devices, which are connected from the wireless router. make to see passwords from all devices.

**Comment by SharadKumar97** [comment]
The codebase has been updated. Closing this issue now.
