### ISSUE TITLE
No need to explicitly mention the installation of urllib2

### ISSUE THREAD

**Issue by Chan9390** [SharadKumar97/OSINT-SPY#2]
`urllib2` now comes pre-installed in Python 2. You dont have to explicitly install that using `pip install urllib2` (as you did at [`install_linux.py`](https://github.com/SharadKumar97/OSINT-SPY/blob/master/install_linux.py#L6) and [`install_windows.py`](https://github.com/SharadKumar97/OSINT-SPY/blob/master/install_windows.py#L5)). 

**Also `pip install urllib2` doesn't work**

**Comment by SharadKumar97** [comment]
Thanks.
