### ISSUE TITLE
email still not working 

### ISSUE THREAD

**Issue by pretech86** [SharadKumar97/OSINT-SPY#20]
i tried python3 python3 osint-spy.py --email example@gmail.com 

and i recieved the followings 
General Details:
--------------------

More details:
--------------------
i try this many times with the same result

**Comment by Sayam753** [comment]
@pretech86  I am able to reproduce this issue. Possible reason can be Invalid access token(API Key) generated from [FullContact API](https://dashboard.fullcontact.com/register). I got a status code of 401 using wrong API Key. Not sure of other cases.

The status code can be checked by adding a print(response.json()) in **email.py** file after getting response from url(line 8).
```python
response = requests.post(url, data=data, headers=headers)
print(response.json()) # Add this line
if response.status_code == 404:
        print('Profile not found')
        return
```

We will soon fix this bug.
Thanks for reporting the issue.

**Comment by OSINT007** [comment]
Just wanted to follow up to see whether the e-mail option is back in working order ? I checked today, and email still keeps giving blank results....this was the best feature. Hopefully, there is a timeline to fix this bug?

**Comment by Sayam753** [comment]
Hi @pretech86 @OSINT007 
The codebase has been updated with more rigorous parsing of data and exception handling. The issue has been resolved.

**Comment by pretech86** [comment]
i get this error 
Invalid authentication. Check API key 

also fullcontact api now paid version i think , can you bypass it althought i entered all api keys
