### ISSUE TITLE
Syntax Error in Chain api 

### ISSUE THREAD

**Issue by Prizrak-X** [SharadKumar97/OSINT-SPY#25]
File "osint-spy.py", line 27
    url = f'https://chain.api.btc.com/v3/block/date/{date}'
                                                          ^
SyntaxError: invalid syntax

**Comment by Sayam753** [comment]
Hi @Prizrak-X 
It maybe because of using f strings. These f strings were introduced in python version >=3.6 . So, can you make sure that the Python's version you are running is >= 3.6?

**Comment by Prizrak-X** [comment]
Yes, it works now thanks!
