### ISSUE TITLE
Unintentional disclosure of VT API-key?

### ISSUE THREAD

**Issue by cstromblad** [SharadKumar97/OSINT-SPY#5]
In the malware.py file, looking at the code for submitting malware samples to VT there appears to be a hardcoded API-key in there?

**Comment by moyamanuel** [comment]
Yes, most likely it's hardcoded so the user doesn't have to generate their own API key. I'm quite sure it's intentional.

**Comment by moyamanuel** [comment]
Right. Most APIs require each user to have their own API key.  Nonetheless, this issue can be address by having the user entering their API key during the initial setup process, and then the API key can be stored in a noSQL database or a text file.

**Comment by SharadKumar97** [comment]
Hi, guys. Sorry about this issue. I forgot to change that. Now I have solved this issue.Thanks
