### ISSUE TITLE
Collect install files into single setup.py file

### ISSUE THREAD

**Issue by mmangione** [SharadKumar97/OSINT-SPY#7]
I attended your talk at CactusCon. Great job.

Why not use a setup.py file so that the install process can be OS ambivalent?

**Comment by SharadKumar97** [comment]
Yes Sure. I will. Thanks

**Comment by moyamanuel** [comment]
You can use the `platform` module from Python if you wish to merge the two setup files together. 

```python
import platform
....

if (platform.system() != "Windows"):
    # Do this for *Nix
else:
   # Do this for Windows.
```

**Comment by SharadKumar97** [comment]
The codebase has been updated, please do a git pull.
